"""empty message

Revision ID: 24a9d5564670
Revises: acb291136346
Create Date: 2022-07-05 19:44:27.647716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a9d5564670'
down_revision = 'acb291136346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'artist', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'show_id')
    # ### end Alembic commands ###
