"""empty message

Revision ID: 42ef29842d0a
Revises: d9a69eac1058
Create Date: 2022-07-05 17:42:39.182389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ef29842d0a'
down_revision = 'd9a69eac1058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'time')
    # ### end Alembic commands ###
