"""empty message

Revision ID: 66c41b260306
Revises: e264ba663538
Create Date: 2022-07-10 19:16:49.890096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c41b260306'
down_revision = 'e264ba663538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seek_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('seek_description', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'talent_hunt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('talent_hunt', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seek_description')
    op.drop_column('artist', 'seek_venue')
    # ### end Alembic commands ###
