"""empty message

Revision ID: b4d7ce3ee3dc
Revises: 45bbc5b2c935
Create Date: 2022-07-07 16:31:53.614176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d7ce3ee3dc'
down_revision = '45bbc5b2c935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('talent_hunt', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'description')
    op.drop_column('venue', 'talent_hunt')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
