"""empty message

Revision ID: c0c6bf974034
Revises: b4d7ce3ee3dc
Create Date: 2022-07-08 15:14:40.929906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c6bf974034'
down_revision = 'b4d7ce3ee3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_show')
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.drop_constraint('venue_relId_fkey', 'venue', type_='foreignkey')
    op.drop_column('venue', 'relId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('relId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venue_relId_fkey', 'venue', 'artist', ['relId'], ['id'])
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    op.create_table('art_show',
    sa.Column('art_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['artist.id'], name='art_show_art_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name='art_show_show_id_fkey'),
    sa.PrimaryKeyConstraint('art_id', 'show_id', name='art_show_pkey')
    )
    # ### end Alembic commands ###
