"""empty message

Revision ID: db8e9ddddd99
Revises: 66c41b260306
Create Date: 2022-07-10 20:50:51.002401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8e9ddddd99'
down_revision = '66c41b260306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'date')
    op.drop_column('artist', 'date')
    # ### end Alembic commands ###
