"""empty message

Revision ID: e264ba663538
Revises: 2a7ab479460d
Create Date: 2022-07-08 17:41:35.526510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e264ba663538'
down_revision = '2a7ab479460d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('talent_hunt', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'Talent_hunt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('Talent_hunt', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'talent_hunt')
    # ### end Alembic commands ###
