"""empty message

Revision ID: f9c6142c72a4
Revises: 628e7f07694d
Create Date: 2022-07-13 14:31:01.611893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c6142c72a4'
down_revision = '628e7f07694d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_column('shows', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
